export { RealtimeError, type RealtimeErrorCode } from './errors'
export { backoffDelayMs, type BackoffOptions } from './backoff'
export type { ConnectionStatus, ConnectionState } from './connection'
export {
  captionEventSchema,
  conversationEventSchema,
  clientCommandSchema,
  participantRoleSchema,
  parseCaptionEvent,
  parseConversationEvent,
  type CaptionEvent,
  type ConversationEvent,
  type ClientCommand,
  type ParticipantRole,
  type ParseResult,
} from './types'
export {
  apiErrorSchema,
  roomSchema,
  sessionStateSchema,
  sessionSummarySchema,
  sessionListSchema,
  sessionStatusSchema,
  createSessionRequestSchema,
  playbackRateSchema,
  rateRequestSchema,
  adminRoomSchema,
  adminRoomListSchema,
  adminSettingsSchema,
  adminSettingsRequestSchema,
  decodeApiError,
  decodeRoom,
  decodeSessionList,
  decodeSessionSummary,
  decodeSessionStatus,
  decodeAdminRooms,
  decodeAdminSettings,
  MIN_PLAYBACK_RATE,
  MAX_PLAYBACK_RATE,
  type DecodeResult,
  type ApiError,
  type Room,
  type SessionState,
  type SessionSummary,
  type SessionStatus,
  type CreateSessionRequest,
  type RateRequest,
  type AdminRoom,
  type AdminSettings,
  type AdminSettingsRequest,
} from './http'
export {
  CaptionStream,
  type CaptionStreamOptions,
  type EventSourceLike,
  type EventSourceFactory,
} from './sse'
export {
  ConversationSocket,
  type ConversationSocketOptions,
  type WebSocketLike,
  type WebSocketFactory,
} from './ws'
